<?php
require("config/config.php");
// Before require header
$title = "Index - Moodwalk";
require("ui/header.php");
?>


<div class="container">
<div class="panel panel-default">
    <div class="panel-heading">Search</div>
    <div class="panel-body">
        <div class="row" id="repo-search-block">
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div id="talkbubble-top" class="hidden-sm hidden-md hidden-lg">
                <?php if (!empty($result[0])){ ?>
                    <p>So, If you have already logged in, Which one do you want to hack ?</p>
                <?php } else { ?>
                    <p>I'm sorry but the first thing you have to do is logging in.</p>
                <?php } ?>
                </div>
                <img src="<?php echo SITE_ROOT;?>/res/img/github.png" alt="Github Repos Displayer"></img>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-5">
                <div id="talkbubble-right" class="hidden-xs">
                <?php if (!empty($result[0])){ ?>
                    <p>So, If you have already logged in, Which one do you want to hack ?</p>
                <?php } else { ?>
                    <p>I'm sorry but the first thing you have to do is logging in.</p>
                <?php } ?>
                </div>
            </div>
        </div>
        <!-- Block for ReactJS -->
        <div id="repo-show-block">

        </div>
    </div>
</div>

<div id="repo-star-show-block">

</div>

<div class="panel panel-success">
    <div class="panel-heading">Tech in this Version (PHP)</div>
    <div class="panel-body">
        <div class="row" id="tech-block">
            <div class="col-xs-12">
                <ul>
                    <li>PHP(Stack LAMP) MySQL</li>
                    <li>HTML/CSS</li>
                    <li>Bootstrap</li>
                    <li>Javascript (React Included)</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="panel panel-default" id="panel-description">
  <div class="panel-heading"><b>Description</b></div>
  <div class="panel-body">
<p class="text-danger">The following contents are generated by Markdown</p>
<p>In this exercise, we are going to ask you to develop a web app using a third party api which is github. (<a href="https://developer.github.com/v3/repos/">https://developer.github.com/v3/repos/</a>)</p>
<h5><a id="Key_features_2"></a>Key features:</h5>
<ul>
<li>Implement an signin/signup page. (In Ruby on Rails, we use the Devise gem:<br>
<a href="https://github.com/plataformatec/devise">https://github.com/plataformatec/devise</a>)</li>
<li>For logged users, implement a search input for a github username (for instance<br>
“octocat”), which returns a list of the user’s repositories.<br>
The search result should first display the user’s avatar.<br>
Then, it should display the user’s repositories sorted by watchers.<br>
For each repository, display “name”, “description”, “watcher count”.</li>
</ul>
<h5><a id="Bonus__Optional_11"></a>[Bonus - Optional]</h5>
<ul>
<li>The logged user can star/unstar a repository.</li>
<li>The logged user can see all previously starred repositories.</li>
<li>Nice UI/UX (Twitter bootstrap ? <a href="https://getbootstrap.com/">https://getbootstrap.com/</a>).</li>
<li>Add tests (Rspec, cucumber).</li>
<li></li>
</ul>
<h5><a id="Technologies_to_use_17"></a>Technologies to use:</h5>
<ul>
<li>Ruby on Rails (Preferable but Optional).</li>
<li>ReactJS (Optional).</li>
<li>Database of your choice.</li>
</ul>
</div></div>
</div>







<?php
require("ui/footer.php");